---
title: "New predictive model"
author: "Derek Corcoran and Nick Watanabe"
date: "March 31, 2017"
output: pdf_document
---

This is a comparison between the new and old 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, caret)
```

```{r, cache=TRUE}
FinalOdds <- readRDS("FinalOdds.rds")

past_gamesFiltPlayoff <- readRDS("past_gamesFiltPlayoff.rds")

DFDates <- readRDS("DFDates.rds")

shotDataTotal2017<- readRDS("shotDataTotal2017.rds")
shotDataTotal2017$GAME_DATE <- ymd(shotDataTotal2017$GAME_DATE)
saveRDS(shotDataTotal2017, "shotDataTotal2017.rds")

shotDatafDef2017 <- readRDS("shotDatafDef2017.rds")

for (i in 1:length(shotDatafDef2017)){
  shotDatafDef2017[[i]]$GAME_DATE <- ymd(shotDatafDef2017[[i]]$GAME_DATE)
}

#####2016
shotDataTotal2016<- readRDS("shotDataTotal2016.rds")
shotDatafDef2016 <- readRDS("shotDatafDef2016.rds")


#####2015

shotDataTotal2015<- readRDS("shotDataTotal2015.rds")
shotDatafDef2015 <- readRDS("shotDatafDef2015.rds")

####2014

shotDataTotal2014<- readRDS("shotDataTotal2014.rds")
shotDatafDef2014 <- readRDS("shotDatafDef2014.rds")


#####2013

shotDataTotal2013<- readRDS("shotDataTotal2013.rds")
shotDatafDef2013 <- readRDS("shotDatafDef2013.rds")

for (i in 1:length(names(shotDatafDef2013))) {
  shotDatafDef2013[[i]]$GAME_DATE <- lubridate::ymd(shotDatafDef2013[[i]]$GAME_DATE)
}
```


```{r, results='asis', warning=FALSE}
stargazer::stargazer(past_gamesFiltPlayoff)
```

You can also embed plots, for example:

```{r}
Model1 <-nls(defAPPS ~ SSasympOff(day, A, lrc, c0), data = DFDates)
DFDates$pred <- predict(Model1)
ceiling(summary(Model1)$coefficients[3])
for_filtering <- DFDates[DFDates$day ==ceiling(summary(Model1)$coefficients[3]),]

DFDates$Season <- as.factor(DFDates$Season)

ggplot(DFDates, aes(x = day, y = defAPPS))+ geom_point(aes(color = Season)) + geom_line(aes(y = pred)) + geom_vline(xintercept = ceiling(summary(Model1)$coefficients[3]))

```

#Plots

* 3d plot
* some shotchart plot
* 

#Tables

* comparison new and old training set
* 
