---
title: "Spatial"
author: "Derek Corcoran"
date: "September 1, 2016"
output: pdf_document
---
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(rjson)
library(grid)
library(gridExtra)
library(png)
library(RCurl)
library(ggplot2)
library(jpeg)
library(hexbin)
library(sp)
library(knitr)
library(raster)
library(rasterVis)
library(dplyr)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}

by_team <- read.csv("~/Sloan/by_team.csv")
by_team <- by_team[-1,-1]
View(by_team)
```

#2015

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
# shot data for Stephen Curry
teamID <- by_team$team_id
teamName <- by_team$team_city
defensiveURL <- list()
shotData <- list()
shotDatafDef <- list()


for (i in 1:length(teamID)){
defensiveURL[[i]] <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2014-15&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=", by_team$team_id[i],"&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2014-15&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotData[[i]] <- fromJSON(file = defensiveURL[[i]], method="C")

# unlist shot data, save into a data frame
shotDatafDef[[i]] <- data.frame(matrix(unlist(shotData[[i]]$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))

# shot data headers
colnames(shotDatafDef[[i]]) <- shotData[[i]]$resultSets[[1]][[2]]

# covert x and y coordinates into numeric
shotDatafDef[[i]]$LOC_X <- as.numeric(as.character(shotDatafDef[[i]]$LOC_X))
shotDatafDef[[i]]$LOC_Y <- as.numeric(as.character(shotDatafDef[[i]]$LOC_Y))
shotDatafDef[[i]]$SHOT_DISTANCE <- as.numeric(as.character(shotDatafDef[[i]]$SHOT_DISTANCE))
}

names(shotDatafDef) <- teamName
# have a look at the data
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
shotURLtotal <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2014-15&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2014-15&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotDataTotal <- fromJSON(file = shotURLtotal, method="C")

# unlist shot data, save into a data frame
shotDataTotal <- data.frame(matrix(unlist(shotDataTotal$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
colnames(shotDataTotal) <- colnames(shotDatafDef[[1]])

# covert x and y coordinates into numeric
shotDataTotal$LOC_X <- as.numeric(as.character(shotDataTotal$LOC_X))
shotDataTotal$LOC_Y <- as.numeric(as.character(shotDataTotal$LOC_Y))
shotDataTotal$SHOT_DISTANCE <- as.numeric(as.character(shotDataTotal$SHOT_DISTANCE))


shotDataTotal2015 <- shotDataTotal

shotDatafDef2015 <- shotDatafDef
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
colnames(shotDataTotal) <- colnames(shotDatafDef[[1]])

# covert x and y coordinates into numeric
shotDataTotal$LOC_X <- as.numeric(as.character(shotDataTotal$LOC_X))
shotDataTotal$LOC_Y <- as.numeric(as.character(shotDataTotal$LOC_Y))
shotDataTotal$SHOT_DISTANCE <- as.numeric(as.character(shotDataTotal$SHOT_DISTANCE))


shotDataTotal2015 <- shotDataTotal

shotDatafDef2015 <- shotDatafDef
```

#2016



```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
defensiveURL <- list()
shotData <- list()
shotDatafDef <- list()


for (i in 1:length(teamID)){
defensiveURL[[i]] <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2015-16&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=", by_team$team_id[i],"&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2015-16&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotData[[i]] <- fromJSON(file = defensiveURL[[i]], method="C")

# unlist shot data, save into a data frame
shotDatafDef[[i]] <- data.frame(matrix(unlist(shotData[[i]]$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))

# shot data headers
colnames(shotDatafDef[[i]]) <- shotData[[i]]$resultSets[[1]][[2]]

# covert x and y coordinates into numeric
shotDatafDef[[i]]$LOC_X <- as.numeric(as.character(shotDatafDef[[i]]$LOC_X))
shotDatafDef[[i]]$LOC_Y <- as.numeric(as.character(shotDatafDef[[i]]$LOC_Y))
shotDatafDef[[i]]$SHOT_DISTANCE <- as.numeric(as.character(shotDatafDef[[i]]$SHOT_DISTANCE))
}

names(shotDatafDef) <- teamName
# have a look at the data
shotDatafDef2016 <- shotDatafDef
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
shotURLtotal <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2015-16&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2015-16&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotDataTotal <- fromJSON(file = shotURLtotal, method="C")

# unlist shot data, save into a data frame
shotDataTotal <- data.frame(matrix(unlist(shotDataTotal$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))
colnames(shotDataTotal) <- colnames(shotDatafDef[[1]])

# covert x and y coordinates into numeric
shotDataTotal$LOC_X <- as.numeric(as.character(shotDataTotal$LOC_X))
shotDataTotal$LOC_Y <- as.numeric(as.character(shotDataTotal$LOC_Y))
shotDataTotal$SHOT_DISTANCE <- as.numeric(as.character(shotDataTotal$SHOT_DISTANCE))


shotDataTotal2016 <- shotDataTotal

```


#2014

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
defensiveURL <- list()
shotData <- list()
shotDatafDef <- list()


for (i in 1:length(teamID)){
defensiveURL[[i]] <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2013-14&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=", by_team$team_id[i],"&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2013-14&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotData[[i]] <- fromJSON(file = defensiveURL[[i]], method="C")

# unlist shot data, save into a data frame
shotDatafDef[[i]] <- data.frame(matrix(unlist(shotData[[i]]$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))

# shot data headers
colnames(shotDatafDef[[i]]) <- shotData[[i]]$resultSets[[1]][[2]]

# covert x and y coordinates into numeric
shotDatafDef[[i]]$LOC_X <- as.numeric(as.character(shotDatafDef[[i]]$LOC_X))
shotDatafDef[[i]]$LOC_Y <- as.numeric(as.character(shotDatafDef[[i]]$LOC_Y))
shotDatafDef[[i]]$SHOT_DISTANCE <- as.numeric(as.character(shotDatafDef[[i]]$SHOT_DISTANCE))
}

names(shotDatafDef) <- teamName
# have a look at the data
shotDatafDef2014 <- shotDatafDef
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}
shotURLtotal <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2013-14&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2013-14&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0", sep = "")

# import from JSON
shotDataTotal <- fromJSON(file = shotURLtotal, method="C")

# unlist shot data, save into a data frame
shotDataTotal <- data.frame(matrix(unlist(shotDataTotal$resultSets[[1]][[3]]), ncol=21, byrow = TRUE))
colnames(shotDataTotal) <- colnames(shotDatafDef[[1]])

# covert x and y coordinates into numeric
shotDataTotal$LOC_X <- as.numeric(as.character(shotDataTotal$LOC_X))
shotDataTotal$LOC_Y <- as.numeric(as.character(shotDataTotal$LOC_Y))
shotDataTotal$SHOT_DISTANCE <- as.numeric(as.character(shotDataTotal$SHOT_DISTANCE))


shotDataTotal2014 <- shotDataTotal

```


```{r, echo=FALSE, message=FALSE, warning=FALSE,}

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='hide'}

court <-  readRDS("court.rds")
```

```{r, cache = TRUE}


ShotComparison <- function(OffTeam, DefTown, SeasondataOff, SeasonDataDef, nbins = 40) {
  #Filter the offensive data of the Offensive Team
  Off <- filter(SeasondataOff, TEAM_NAME == OffTeam)
  #Filter the Deffensive data of the Defensive team
  deff <- SeasonDataDef[names(SeasonDataDef) == DefTown][[1]]
  #Get the maximum and minumum values for x and y
  xbnds <- range(c(SeasondataOff$LOC_X, deff$LOC_X))
  ybnds <- range(c(SeasondataOff$LOC_Y, deff$LOC_Y))
  #Make hexbin dataframes out of the teams
  makeHexData <- function(df) {
    h <- hexbin(df$LOC_X, df$LOC_Y, nbins, xbnds = xbnds, ybnds = ybnds, IDs = TRUE)
    data.frame(hcell2xy(h),
               PPS = tapply(as.numeric(as.character(df$SHOT_MADE_FLAG))*ifelse(tolower(df$SHOT_TYPE) == "3pt field goal", 3, 2), h@cID, FUN = function(z) sum(z)/length(z)),
               ST = tapply(df$SHOT_MADE_FLAG, h@cID, FUN = function(z) length(z)),
               cid = h@cell)
  }
  ##Total NBA data
  Totalhex <- makeHexData(SeasondataOff)
  ##Defensive team data
  Defhex <- makeHexData(deff)
  ##Offensive team data
  Offhex <- makeHexData(Off)
  #Merge offensive and deffensive data with total data by Cell id
  DeffbyCell <- merge(Totalhex, Defhex, by = "cid", all = T)
  OffByCell <- merge(Totalhex, Offhex, by = "cid", all = T)
  ##  when calculating the difference empty cells should count as 0
  DeffbyCell$PPS.x[is.na(DeffbyCell$PPS.x)] <- 0
  DeffbyCell$PPS.y[is.na(DeffbyCell$PPS.y)] <- 0
  DeffbyCell$ST.y[is.na(DeffbyCell$ST.y)] <- 0

  OffByCell$PPS.x[is.na(OffByCell$PPS.x)] <- 0
  OffByCell$PPS.y[is.na(OffByCell$PPS.y)] <- 0
  OffByCell$ST.y[is.na(OffByCell$ST.y)] <- 0
  #  make a "difference" data.frame
  DiffDeff <- data.frame(x = ifelse(is.na(DeffbyCell$x.x), DeffbyCell$x.y, DeffbyCell$x.x),
                        y = ifelse(is.na(DeffbyCell$y.x), DeffbyCell$y.y, DeffbyCell$y.x),
                        PPS= DeffbyCell$PPS.y - DeffbyCell$PPS.x,
                        cid= DeffbyCell$cid, 
                        ST = DeffbyCell$ST.y)
  
  DiffOff <- data.frame(x = ifelse(is.na(OffByCell$x.x), OffByCell$x.y, OffByCell$x.x),
                        y = ifelse(is.na(OffByCell$y.x), OffByCell$y.y, OffByCell$y.x),
                        PPS= OffByCell$PPS.y - OffByCell$PPS.x,
                        ST = OffByCell$ST.x,
                        cid = OffByCell$cid, 
                        ST = OffByCell$ST.y)
  #make team comparisons
  Comparison <- merge(DiffOff, DiffDeff, by = "cid", all = T) 
  Comparison <- Comparison[,-c(6:7)]
  Comparison$Diff <- c(Comparison$PPS.x + Comparison$PPS.y)
  
  
  PPSAA <- weighted.mean((Comparison$PPS.x + Comparison$PPS.y), Comparison$ST.x)
  
  OFF <- ggplot(DiffOff)  + 
    annotation_custom(court, -250, 250, -52, 418) +
    geom_hex(aes(x = x, y = y, fill = PPS),
             stat = "identity", alpha = 0.8) +
    guides(alpha = FALSE, size = FALSE) +
    coord_fixed()  +theme(line = element_blank(),
                          axis.title.x = element_blank(),
                          axis.title.y = element_blank(),
                          axis.text.x = element_blank(),
                          axis.text.y = element_blank(),
                          legend.title = element_blank(),
                          plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle(paste(OffTeam, "Offensive\n Shot Chart", sep = " ")) + scale_fill_gradient2(name="Off PPS")
  DEF <- ggplot(DiffDeff)  + 
    annotation_custom(court, -250, 250, -52, 418) +
    geom_hex(aes(x = x, y = y, fill = PPS),
             stat = "identity", alpha = 0.8) +
    guides(alpha = FALSE, size = FALSE) +
    
    coord_fixed()  +theme(line = element_blank(),
                          axis.title.x = element_blank(),
                          axis.title.y = element_blank(),
                          axis.text.x = element_blank(),
                          axis.text.y = element_blank(),
                          legend.title = element_blank(),
                          plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle(paste(DefTown, "defensive\n Shot Chart", sep = " ")) + scale_fill_gradient2(name="Def PPS")
  
  COMP <- ggplot(Comparison)  + 
    annotation_custom(court, -250, 250, -52, 418) +
    geom_hex(aes(x = x.x, y = y.x, fill = Diff),
             stat = "identity", alpha = 0.8) +
    guides(alpha = FALSE, size = FALSE) +
    
    coord_fixed()  +theme(line = element_blank(),
                          axis.title.x = element_blank(),
                          axis.title.y = element_blank(),
                          axis.text.x = element_blank(),
                          axis.text.y = element_blank(),
                          legend.title = element_blank(),
                          plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle("Comparison\n Shot Chart") + scale_fill_gradient2(name="Difference\n PPS")

  grid.arrange(DEF, OFF, COMP, ncol=3)
  
  return(list(Off = DiffOff, deff = DiffDeff, Comparison = Comparison, Total = Totalhex, PPSAA = PPSAA))
}

Com1 <- ShotComparison(OffTeam = "Cleveland Cavaliers", DefTown = "Philadelphia", SeasondataOff = shotDataTotal2016, SeasonDataDef = shotDatafDef2016, nbins = 40)

Com1$PPSAA

Com2 <- ShotComparison(OffTeam = "Philadelphia 76ers", DefTown = "Cleveland", SeasondataOff = shotDataTotal2016, SeasonDataDef = shotDatafDef2016, nbins = 40)

Com2$PPSAA
```

```{r, cache=TRUE}
ShotComparison <- function(OffTeam, DefTown, SeasondataOff, SeasonDataDef, nbins = 30) {
  #Filter the offensive data of the Offensive Team
  Off <- filter(SeasondataOff, TEAM_NAME == OffTeam)
  #Filter the Deffensive data of the Defensive team
  deff <- SeasonDataDef[names(SeasonDataDef) == DefTown][[1]]
  #Get the maximum and minumum values for x and y
  xbnds <- range(c(SeasondataOff$LOC_X, deff$LOC_X))
  ybnds <- range(c(SeasondataOff$LOC_Y, deff$LOC_Y))
  #Make hexbin dataframes out of the teams
  makeHexData <- function(df) {
    h <- hexbin(df$LOC_X, df$LOC_Y, nbins, xbnds = xbnds, ybnds = ybnds, IDs = TRUE)
    data.frame(hcell2xy(h),
               PPS = tapply(as.numeric(as.character(df$SHOT_MADE_FLAG))*ifelse(tolower(df$SHOT_TYPE) == "3pt field goal", 3, 2), h@cID, FUN = function(z) sum(z)/length(z)),
               ST = tapply(df$SHOT_MADE_FLAG, h@cID, FUN = function(z) length(z)),
               cid = h@cell)
  }
  ##Total NBA data
  Totalhex <- makeHexData(SeasondataOff)
  ##Defensive team data
  Defhex <- makeHexData(deff)
  ##Offensive team data
  Offhex <- makeHexData(Off)
  #Merge offensive and deffensive data with total data by Cell id
  DeffbyCell <- merge(Totalhex, Defhex, by = "cid", all = T)
  OffByCell <- merge(Totalhex, Offhex, by = "cid", all = T)
  ##  when calculating the difference empty cells should count as 0
  DeffbyCell$PPS.x[is.na(DeffbyCell$PPS.x)] <- 0
  DeffbyCell$PPS.y[is.na(DeffbyCell$PPS.y)] <- 0
  DeffbyCell$ST.y[is.na(DeffbyCell$ST.y)] <- 0

  OffByCell$PPS.x[is.na(OffByCell$PPS.x)] <- 0
  OffByCell$PPS.y[is.na(OffByCell$PPS.y)] <- 0
  OffByCell$ST.y[is.na(OffByCell$ST.y)] <- 0
  #  make a "difference" data.frame
  DiffDeff <- data.frame(x = ifelse(is.na(DeffbyCell$x.x), DeffbyCell$x.y, DeffbyCell$x.x),
                        y = ifelse(is.na(DeffbyCell$y.x), DeffbyCell$y.y, DeffbyCell$y.x),
                        PPS= DeffbyCell$PPS.y - DeffbyCell$PPS.x,
                        cid= DeffbyCell$cid, 
                        ST = DeffbyCell$ST.y)
  
  DiffOff <- data.frame(x = ifelse(is.na(OffByCell$x.x), OffByCell$x.y, OffByCell$x.x),
                        y = ifelse(is.na(OffByCell$y.x), OffByCell$y.y, OffByCell$y.x),
                        PPS= OffByCell$PPS.y - OffByCell$PPS.x,
                        ST = OffByCell$ST.x,
                        cid = OffByCell$cid, 
                        ST = OffByCell$ST.y)
  #make team comparisons
  Comparison <- merge(DiffOff, DiffDeff, by = "cid", all = T) 
  Comparison <- Comparison[,-c(6:7)]
  Comparison$Diff <- c(Comparison$PPS.x + Comparison$PPS.y)
  
  
  PPSAA <- weighted.mean((Comparison$PPS.x + Comparison$PPS.y), Comparison$ST.x)
  print(PPSAA)
  # OFF <- ggplot(DiffOff)  + 
  #   annotation_custom(court, -250, 250, -52, 418) +
  #   geom_hex(aes(x = x, y = y, fill = PPS),
  #            stat = "identity", alpha = 0.8) +
  #   guides(alpha = FALSE, size = FALSE) +
  #   coord_fixed()  +theme(line = element_blank(),
  #                         axis.title.x = element_blank(),
  #                         axis.title.y = element_blank(),
  #                         axis.text.x = element_blank(),
  #                         axis.text.y = element_blank(),
  #                         legend.title = element_blank(),
  #                         plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle(paste(OffTeam, "Offensive\n Shot Chart", sep = " ")) + scale_fill_gradient2(name="Off PPS")
  # DEF <- ggplot(DiffDeff)  + 
  #   annotation_custom(court, -250, 250, -52, 418) +
  #   geom_hex(aes(x = x, y = y, fill = PPS),
  #            stat = "identity", alpha = 0.8) +
  #   guides(alpha = FALSE, size = FALSE) +
  #   
  #   coord_fixed()  +theme(line = element_blank(),
  #                         axis.title.x = element_blank(),
  #                         axis.title.y = element_blank(),
  #                         axis.text.x = element_blank(),
  #                         axis.text.y = element_blank(),
  #                         legend.title = element_blank(),
  #                         plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle(paste(DefTown, "defensive\n Shot Chart", sep = " ")) + scale_fill_gradient2(name="Def PPS")
  # 
  # COMP <- ggplot(Comparison)  + 
  #   annotation_custom(court, -250, 250, -52, 418) +
  #   geom_hex(aes(x = x.x, y = y.x, fill = Diff),
  #            stat = "identity", alpha = 0.8) +
  #   guides(alpha = FALSE, size = FALSE) +
  #   
  #   coord_fixed()  +theme(line = element_blank(),
  #                         axis.title.x = element_blank(),
  #                         axis.title.y = element_blank(),
  #                         axis.text.x = element_blank(),
  #                         axis.text.y = element_blank(),
  #                         legend.title = element_blank(),
  #                         plot.title = element_text(size = 17, lineheight = 1.2, face = "bold")) + ggtitle("Comparison\n Shot Chart") + scale_fill_gradient2(name="Difference\n PPS")
  # 
  # grid.arrange(DEF, OFF, COMP, ncol=3)
  
  return(PPSAA)
}


Offensive_teams <- as.character(unique(shotDataTotal2016$TEAM_NAME))

defenseve_names <- names(shotDatafDef2016)
df2016 <- data.frame(matrix(ncol = 30, nrow = 30))
colnames(df2016) <- as.character(unique(shotDataTotal2016$TEAM_NAME))
rownames(df2016) <- names(shotDatafDef2016)

system.time(for (i in 1:length(Offensive_teams)) {
  Offensive_team <- Offensive_teams[i]
  for (j in 1:length(defenseve_names)){
    df2016[j,i] <- ShotComparison(OffTeam = Offensive_team, DefTown =                        defenseve_names[j], SeasondataOff = shotDataTotal2016, SeasonDataDef = shotDatafDef2016, nbins = 30)
  }
})


```

```{r, cache=TRUE}
write.csv(df2016, "datos2016.csv")
colMeans(df2016, na.rm = TRUE)
min(df2016)
```