---
title: "Standings"
author: "Derek Corcoran"
date: "February 3, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Projected Eastern Standings


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(DT)
E <- structure(list(Team = structure(c(3L, 6L, 14L, 8L, 15L, 1L, 7L, 
4L, 12L, 5L, 10L, 11L, 9L, 13L, 2L), .Label = c("Atl", "Bkn", 
"Bos", "Cha", "Chi", "Cle", "Det", "Ind", "Mia", "Mil", "NY", 
"ORL", "Phi", "Tor", "Was"), class = "factor"), Current.W = c(31L, 
33L, 30L, 26L, 29L, 29L, 22L, 23L, 19L, 25L, 21L, 22L, 20L, 18L, 
9L), Current.L = c(18L, 15L, 20L, 22L, 20L, 21L, 27L, 27L, 32L, 
25L, 27L, 29L, 30L, 31L, 40L), Conference = structure(c(1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = "East", class = "factor"), 
    Projected.W = c(54L, 49L, 49L, 48L, 46L, 43L, 40L, 39L, 38L, 
    37L, 37L, 37L, 36L, 30L, 20L), Projected.L = c(28L, 33L, 
    33L, 34L, 36L, 39L, 42L, 43L, 44L, 45L, 45L, 45L, 46L, 52L, 
    62L)), .Names = c("Team", "Current.W", "Current.L", "Conference", 
"Projected.W", "Projected.L"), class = "data.frame", row.names = c(NA, 
-15L))
```

```{r, echo=FALSE}
options(DT.options = list(pageLength = 20, language = list(search = 'Filter:')))

DT::datatable(E)
```

